version: "3"
services:
  user-service:
    image: keep-fit/user:2.0.0
    container_name: user-service
    ports:
      - "2022:8080"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 5
        window: 30s
  plan-service:
    image: keep-fit/plan:2.0.0
    container_name: plan-service
    ports:
      - "2021:8080"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 5
        window: 30s
  nutrition-service:
    image: keep-fit/nutrition:1.9.2
    container_name: nutrition-service
    ports:
      - "2020:8080"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 5
        window: 30s
  notification-service:
    image: keep-fit/notification:1.4.0
    container_name: notification-service
    environment: 
      - EMAIL_NAME
      - EMAIL_PASSWORD
    ports:
      - "2030:5000"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 5
        window: 30s
  orchestrator-service:
    image: keep-fit/orchestrator:2.0.0
    container_name: orchestrator-service
    environment:
      - HOST_USER
      - HOST_PLAN
      - HOST_NUTRITION
      - HOST_NOTIFICATION
    ports:
      - "2025:8080"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 5
        window: 30s
  frontend-service:
    image: keep-fit/frontend:2.0.0
    container_name: frontend-service
    ports:
      - "3001:3000"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 5
        window: 30s
